{
  stateName:   'Louisiana',
  agencyName:  'Louisiana Gaming Control Board (LGCB) + Louisiana Racing Commission (LRC)',
  agencyShort: 'LGCB + LRC',
  tabs: {
    tab1: { label: 'Pari-Mutuel / Racing',  sourceLabel: 'LRC Racing System' },
    tab2: { label: 'Sports Wagering',        sourceLabel: 'Sportsbook Platform' },
    tab3: { label: 'Charitable Gaming',      sourceLabel: 'Charitable Gaming Registry' },
    tab4: { label: 'Patron Identity',        badge: 'Powered by P3RL + Delta Sharing' },
  },
  operators: [
    { id: 'op1', name: 'Fair Grounds / TwinSpires', vertical: 'tab1' },
    { id: 'op2', name: 'Delta Downs ADW',            vertical: 'tab1' },
    { id: 'op3', name: 'FanDuel Sportsbook',         vertical: 'tab2' },
    { id: 'op4', name: 'DraftKings Sportsbook',      vertical: 'tab2' },
    { id: 'op5', name: 'Caesars Sportsbook',         vertical: 'tab2' },
    { id: 'op6', name: 'Charitable Gaming Registry', vertical: 'tab3' },
  ],
  dataScale: {
    tab1_base_wager_volume:    900_000,
    tab2_base_wager_volume:  1_500_000,
    tab3_base_receipts:        380_000,
    patron_population:         220_000,
    active_exclusions:           4_200,
  },
  tab3_orgs: [
    'New Orleans Knights of Columbus', 'Baton Rouge Lions Club', 'Lafayette Rotary Foundation',
    'Shreveport VFW Post 1', 'Acadiana Elks Lodge', 'Louisiana 4-H Foundation',
    'Covington Kiwanis Club', 'Lake Charles American Legion', 'Monroe AMVETS Post 12',
    'Metairie Catholic Charities', 'Houma Moose Lodge', 'Natchitoches Community Foundation',
    'Alexandria Eagles Aerie', 'Opelousas Youth Sports', 'Hammond Civitan Club',
    'Ruston Shrine Club', 'Jennings Rotary Club', 'Thibodaux Historical Society',
    'Slidell Area United Way', 'Bastrop Optimist Club', 'Crowley VFW Auxiliary',
    'Sulphur American Legion', 'Morgan City Lions Club', 'Gonzales Kiwanis',
    'New Iberia Fraternal Order', 'Denham Springs Jaycees', 'Kenner St. Vincent dePaul',
    'Westwego Community Foundation', 'Breaux Bridge Rotary', 'Minden Eagles Aerie',
    'Plaquemine Veterans Foundation', 'Bogalusa AMVETS Post 8', 'Gretna Elks Lodge',
    'Mandeville Youth Sports', 'Abbeville Lions Club', 'Pineville Shrine Club',
    'Tallulah Area United Way', 'DeRidder Kiwanis', 'Eunice Civitan Club',
    'Ferriday VFW Auxiliary',
  ],
  seasonLabel: 'Current Season (Sep–Apr)',
  seasonStart: '2025-09-01',
  seasonEnd:   '2026-04-30',
  stateWeights: [
    ['LA', 350], ['TX', 30], ['MS', 18], ['AR', 10], ['TN', 8],
    ['AL', 6],   ['FL', 5],  ['GA', 3],  ['OK', 2],  ['MO', 2],
  ],
}